externalsecrets:
  enabled: false

env:
- name: DEV
  value: "true"
- name: SVELTE_APP_USERNAME
  value: admin
- name: SVELTE_APP_PASSWORD
  value: admin


# gras-deploy:
gras:
  # gras: 
  #   ssl: false
  grapi:
    ssl: false
    dev: true
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
  gruim:
    ssl: false
    dev: true
    autoscaling:
      minReplicas: 1
      maxReplicas: 1


ingress:
  enabled: true
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

replicaCount: 1
