env:
- name: DEV
  value: "true"
- name: SVELTE_APP_USERNAME
  value: admin
- name: SVELTE_APP_PASSWORD
  value: jcs-bo-admin


gras-deploy: 
  # gras: 
  #   ssl: false
  grapi:
    ssl: false
    dev: true
  gruim:
    ssl: false
    dev: true


ingress:
  enabled: true
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
