externalsecrets:
  enabled: false

env:
- name: SVELTE_APP_REMOTE_URL
  value: "http://myapp-dev-ns99-myapp-gruim.test"
- name: CONTAINER_NAME
  value: "myappdevns99myappgruim"
# - name: DEV
#   value: "true"
- name: SVELTE_APP_USERNAME
  value: admin
- name: SVELTE_APP_PASSWORD
  value: password


gras-deploy: 
  # gras: 
  #   ssl: false
  grapi:
    ssl: false
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
  gruim:
    ssl: false
    autoscaling:
      minReplicas: 1
      maxReplicas: 1


ingress:
  enabled: true
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

replicaCount: 1
