{{- if .Values.externalsecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Namespace }}-aws-secret-store-jcs
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: awssm-secret-jcs 
            namespace: grpl-system
          secretAccessKeySecretRef:
            key: secret-access-key
            name: awssm-secret-jcs 
            namespace: grpl-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jcs-admin-secret
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: grapple/jcscherrer/admin
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Release.Namespace }}-aws-secret-store-jcs
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: jcs-admin-secret
---
{{- if .Values.bexio.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jcs-bexio
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: grapple/jcscherrer/bexio
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Release.Namespace }}-aws-secret-store-jcs
  target:
    creationPolicy: Owner
    name: jcs-bexio
---
{{- end }}
{{- end }}
