{{- if .Values.externalsecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: awssm-secret-jcs 
            namespace: grpl-system
          secretAccessKeySecretRef:
            key: secret-access-key
            name: awssm-secret-jcs 
            namespace: grpl-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jcs-admin-secret
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: cloud20x/jcscherrer/admin
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: jcs-admin-secret
---
{{- end }}
